### PR TITLE
Added commas to protocols.csv

### PR DESCRIPTION
**Pull request by wanderer**

### CODE REVIEW

**Comment by lgierth** [comment]
Why the need for commas, aren't tabs fine?

**Comment by wanderer** [comment]
@lgierth because github make it look cool and searchable if you do https://github.com/wanderer/multiaddr/blob/master/protocols.csv 

Let me know which way you prefer!

**Comment by bcavileer** [comment]
+1
I guess I don't need to submit my pull request ;)

**Comment by jbenet** [comment]
sure sgtm

**Comment by jbenet** [comment]
hopefully nothing expecting tabs broke

**Pull request merged**
